export const SET_IS_MESSAGE_POPUP_OPENED = 'APP/SET_IS_MESSAGE_POPUP_OPENED';
export const SET_IS_POPUP_OPENED = 'APP/SET_IS_POPUP_OPENED';

export const SET_USERS = 'USER/SET_USERS';
export const CURRENT_USER = 'USER/CURRENT_USER';
export const UPDATE_USER = 'USER/UPDATE_USER';
export const FILTER_TRACKED = 'USER/FILTER_TRACKED';